### ISSUE TITLE
手机端Termux，使用本脚本一些问题

### ISSUE THREAD

**Issue by matsurinya** [xxyz30/skyland-auto-sign#1]
`Traceback (most recent call last):
  File "/data/data/com.termux/files/home/skyland.py", line 62, in <module>
    do_sign()
  File "/data/data/com.termux/files/home/skyland.py", line 58, in do_sign
    f'角色{i.get("nickName")}({i.get("channelName")})签到成功，获得了{resp.get("resource").get("name")}×{resp.get("count")}'
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'`
Python版本：Python 3.11.5
终端：手机端Termux
这个是每次签到都会出现的，重复签到倒是没有报错

**Comment by matsurinya** [comment]
能正常签到，但是每次都报错

**Comment by xxyz30** [comment]
我看看

**Comment by xxyz30** [comment]
修好了，你试试看

**Comment by matsurinya** [comment]
明天登录试试看

**Comment by matsurinya** [comment]
正常了 ，使用令牌是能登录不报错的的，使用验证码会提示'status'登不上，有可能是我后台有令牌数据？

**Comment by xxyz30** [comment]
哦这个问题可能是人机验证的问题，用验证码登录是这样的

**Comment by xxyz30** [comment]
或者用最新代码再登一下？

**Comment by xxyz30** [comment]
确实有这个问题，现在修复了。用最新的代码试试看

**Comment by matsurinya** [comment]
好的 今晚试试
