### ISSUE TITLE
token过期问题

### ISSUE THREAD

**Issue by qwedc001** [xxyz30/skyland-auto-sign#5]
这个token本身在电脑端退出登录的情况下也会失效来着，这样的话多个账号同时登录是如何实现的，使用不同的浏览器登入吗？
如果是的话，麻烦在docs里写一下吧，谢谢

**Comment by qwedc001** [comment]
刚刚自己尝试了一下，确实是需要多开浏览器，并且无痕浏览器关闭后不会导致token失效，不过有没有失效时间就是另一码事了，等着明天再测试一下

**Comment by xxyz30** [comment]
可以清除浏览器缓存做到，反正就是不能登出
