### ISSUE TITLE
能否适配青龙面板？

### ISSUE THREAD

**Issue by PianCat** [xxyz30/skyland-auto-sign#6]
其他类似的项目：
[https://github.com/OreosLab/checkinpanel](url)

感觉如果适配了的话很多平台也都能用了，包括家用的小NAS之类的。

**Comment by PianCat** [comment]
青龙面板可以通过读取环境变量 `PWD` 的方式获取文件目录。
其中可以在GUI中调整的 `配置文件` 位于 $PWD/config 目录下
感觉可以将TOKEN文件放进去，然后跑脚本去读取那个文件然后来进行签到适配

**Comment by xxyz30** [comment]
这个执行的脚本能自己创建文件不，能创建的话只需要按照普通电脑的运行方法运行就行了吧？

**Comment by PianCat** [comment]
> 这个执行的脚本能自己创建文件且不会被删除不，能创建的话只需要按照普通电脑的运行方法运行就行了吧？

倒是不会被删，但是没法交互，也没法比较方便地修改TOKEN

**Comment by Zerolouis** [comment]
我改了一个青龙面板的，token写在环境变量 https://github.com/Zerolouis/skyland_auto_sign_qinglong
