### ISSUE TITLE
签到失败

### ISSUE THREAD

**Issue by solitudealma** [xxyz30/skyland-auto-sign#7]
可能是多次请求github api导致状态码是503，是不是搞个失败重试会比较完善点，毕竟api不能保证它一直都是可用状态，不过action失败会邮箱提示就是了
![image](https://github.com/xxyz30/skyland-auto-sign/assets/57446969/12a3f827-3a95-47c1-9c86-b86b5bb4010e)

**Comment by xxyz30** [comment]
这是github的失败还是我脚本失败了？脚本失败的话应该会有中文提示的吧？

**Comment by solitudealma** [comment]
> 这是github的失败还是我脚本失败了？脚本失败的话应该会有中文提示的吧？

不是脚本的问题吧，它不是会下载依赖什么的吗，过程中会请求github的api，可能被认为太频繁了

**Comment by xxyz30** [comment]
等下你为啥要这么频繁调用github的API？不是一天调用一次就好了吗）

**Comment by xxyz30** [comment]
我的脚本里没有调用github的api的，这个下载依赖的问题我不是很清楚咋解决？
@LogicDX342

**Comment by solitudealma** [comment]
> 等下你为啥要这么频繁调用github的API？不是一天调用一次就好了吗）

没有，因为在maa那里看到的issue，然后两个仓库对比，我以为另一个仓库的cred是你这里的token，然后试了几次，再去看readme才发现不是直接拿到cred

**Comment by solitudealma** [comment]
> 我的脚本里没有调用github的api的，这个下载依赖的问题我不是很清楚咋解决？ @LogicDX342

这不是你的问题，就是build的时候action自己执行的，和代码无关，因为要建立环境吧

**Comment by LogicDX342** [comment]
貌似是GitHub自己的问题，现在应该好了
https://github.com/actions/checkout/issues/672
